name: Cypress

on: ['pull_request', 'push']

jobs:
  cypress:
    name: Run Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup Node 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Cypress dependencies
        run: npm install

      - name: Cypress Run
        uses: cypress-io/github-action@v3.0.2
        with:
          # we have already installed all dependencies above
          install: false
          record: false
          group: https://seltzerpr.wpengine.com
          working-directory: ./ui-tests
          # Wrap cypress inside of a percy run
          command-prefix: 'percy exec --verbose --'
        env:
          TZ: America/Los_Angeles
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_BASE_URL: https://seltzerpr.wpengine.com
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
